[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm build"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "web"
envVars = [
  "DATABASE_URL",
  "REDIS_URL",
  "NEXTAUTH_URL",
  "NEXTAUTH_SECRET",
  "DISCORD_CLIENT_ID",
  "DISCORD_CLIENT_SECRET",
  "UPLOADTHING_TOKEN",
  "OPENAI_API_KEY",
  "ANTHROPIC_API_KEY",
  "STABILITY_API_KEY",
  "STABILITY_AI_API_URL"
]

[[services]]
name = "worker"
startCommand = "pnpm worker:start"
envVars = [
  "DATABASE_URL",
  "REDIS_URL",
  "UPLOADTHING_TOKEN",
  "OPENAI_API_KEY",
  "ANTHROPIC_API_KEY",
  "STABILITY_API_KEY",
  "STABILITY_AI_API_URL"
]
