[build]
builder = "NIXPACKS"
buildCommand = "npm install"
nodeVersion = "20.11.1"

[deploy]
startCommand = "npm run worker:start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "queue-worker"
numReplicas = 1
envVars = [
  "DATABASE_URL",
  "REDIS_URL",
  "UPLOADTHING_TOKEN",
  "OPENAI_API_KEY",
  "ANTHROPIC_API_KEY",
  "STABILITY_API_KEY",
  "STABILITY_AI_API_URL",
  "NODE_ENV"
]

[services.deploy]
healthcheck = {
  command = "node -e \"console.log('Environment:', process.env.NODE_ENV, 'UploadThing:', !!process.env.UPLOADTHING_TOKEN)\"",
  interval = "5m",
  timeout = "10s",
  retries = 3
}