[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "npm run worker:start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[[services]]
name = "queue-worker"
envVars = [
  "DATABASE_URL",
  "REDIS_URL",
  "UPLOADTHING_TOKEN",
  "OPENAI_API_KEY",
  "ANTHROPIC_API_KEY",
  "STABILITY_API_KEY",
  "STABILITY_AI_API_URL"
]